Changes spans to divs
adaptlearning/adapt-contrib-triggered pull request #23
Opened 2017-11-20 16:10 UTC by simondate

Because `span` tags use `display: inline-block` rather than `display: block` if text goes over one line it doesn't display very well. Makes more sense to be a div instead. Before and after below.

<img width="347" alt="screen shot 2017-11-20 at 16 09 52" src="https://user-images.githubusercontent.com/1676635/33028240-4ce7dff4-ce0d-11e7-9d3b-1f98c69dcdd9.png">

<img width="365" alt="screen shot 2017-11-20 at 16 10 06" src="https://user-images.githubusercontent.com/1676635/33028243-4f024482-ce0d-11e7-84ff-8f2e557ae3c6.png">

2021-06-01 13:08 UTC, oliverfoster commented on templates/triggered-hide-button.hbs
> +    <div class="triggered-button-text">{{{_triggered.hideButton.buttonText}}}</span>
I concur

2021-06-29 15:56 UTC, oliverfoster commented
@simondate any progress?

2021-06-30 13:00 UTC, simondate commented
@oliverfoster @cahirodoherty-learningpool all done.

2021-06-30 14:08 UTC, cahirodoherty-learningpool requested changes

2021-06-30 14:08 UTC, cahirodoherty-learningpool commented on templates/triggered-show-button.hbs
> +<div class="triggered-button-text">{{{_triggered.showButton.buttonText}}}</span>
Missed the replacement from this hbs file

2021-06-30 15:11 UTC, oliverfoster approved these changes

2021-06-30 15:14 UTC, cahirodoherty-learningpool commented
@simondate I think you accidentally reverted the triggered-show-button.hbs div back into a span. Can you have another look please, and let me know if this is intended?

2021-06-30 15:19 UTC, simondate commented
@cahirodoherty-learningpool my mistake!

2021-06-30 15:23 UTC, cahirodoherty-learningpool approved these changes

2021-06-30 15:23 UTC, oliverfoster approved these changes

2021-06-30 15:23 UTC, merged